In [172]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [173]:
df = pd.read_csv('../Dataset/movies_metadata.csv')

In [174]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [176]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [177]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [178]:
df.duplicated().sum()

np.int64(13)

In [179]:
df.drop_duplicates(inplace=True)

In [180]:
df.duplicated().sum()

np.int64(0)

In [181]:
df = df[['genres', 'imdb_id', 'title', 'overview', 'tagline']]

In [182]:
df.columns

Index(['genres', 'imdb_id', 'title', 'overview', 'tagline'], dtype='object')

### Working with null values

In [183]:
df.isnull().sum()

genres          0
imdb_id        17
title           6
overview      954
tagline     25045
dtype: int64

In [184]:
df = df.dropna(subset=['title', 'imdb_id'])

In [185]:
df['overview'] = df['overview'].fillna('')

In [186]:
df['tagline'] = df['tagline'].fillna('')

In [187]:
df.isnull().sum()

genres      0
imdb_id     0
title       0
overview    0
tagline     0
dtype: int64

### Working with genres

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45430 entries, 0 to 45465
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    45430 non-null  object
 1   imdb_id   45430 non-null  object
 2   title     45430 non-null  object
 3   overview  45430 non-null  object
 4   tagline   45430 non-null  object
dtypes: object(5)
memory usage: 2.1+ MB

In [189]:
print(df['genres'].iloc[0])

[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]

In [190]:
# convert the string into a Python list
import ast

df['genres'] = df['genres'].apply(ast.literal_eval)

In [ ]:
# single string
df['genres'] = df['genres'].apply(
    lambda x: ' '.join(item['name'] for item in x)
)

In [193]:
print(df['genres'].iloc[0])

Animation Comedy Family

In [195]:
df.head()

,genres,imdb_id,title,overview,tagline
0,Animation Comedy Family,tt0114709,Toy Story,"Led by Woody, Andy's toys live happily in his ...",
1,Adventure Fantasy Family,tt0113497,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!
2,Romance Comedy,tt0113228,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...
3,Comedy Drama Romance,tt0114885,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...
4,Comedy,tt0113041,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...

In [196]:
df['tags'] = df['overview']+ " " + df['genres'] +" "+ df['tagline']

### Using NLP

In [200]:
print(df['tags'][1])

When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!

Remove the punctuations mark

Remove the stop Words

Lemmetization

Convert into TF-IDF vector

In [201]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [202]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...

True

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
def preprocess_text(text):

  #lowercase
  text = str(text).lower()
  
  #removed the punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [205]:
df['tags'] = df['tags'].apply(preprocess_text)

In [206]:
df = df.reset_index(drop = True)

indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45425
Century of Birthing            45426
Betrayal                       45427
Satan Triumphant               45428
Queerama                       45429
Length: 45430, dtype: int64

In [207]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

tfidf_matrix = tfidf.fit_transform(df['tags'])

In [209]:
from sklearn.metrics.pairwise import cosine_similarity

In [210]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [211]:
recommend('Avatar',5)

26535                  Avatar 2
13880      The Inhabited Island
26541            Thor: Ragnarok
43415    Moontrap: Target Earth
14116      The Three Musketeers
Name: title, dtype: object